# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7342de2c61ce881006f898362c6016b31f06ae958504ce5d0d28ea85a8171050fa5b423eb655a9722c62daa6eae23b4c980aab6c7ed5006a0604b63db49f3234

test:
  secret_key_base: 2d6c8b243a740ac5f339002357e147680fd6fd48ece850ccdaf311c82f1377d17ec8ff31cebd315153e4f0ae1f95e3fc0a5fcbb3da5777bcf76d6b7152be185c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
